#!/bin/bash
set -ex

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${SCRIPT_DIR}/versions.sh

# original docker build command
echo "overwriting docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME ."

echo -e $NGINX_VERSIONS | while read nginx_version
do
        echo $nginx_version
        # The new image tag will include the version of our software, prefixed to the os image we're currently building
        IMAGE_TAG="${DOCKER_REPO}:${nginx_version}-${DOCKER_TAG}"

        docker build -f Dockerfile --build-arg NGINX_VERSION=${nginx_version} -t ${IMAGE_TAG} ../
done